### ISSUE TITLE
Expected Time Release of Checkpoints

### ISSUE THREAD

**Issue by MingyuKim87** [mlvlab/DDMI#1]
Thanks for sharing the official repository of DDMI paper. 
When I tried to run training codes (including auto encoder / diffusion), it takes at least 4 days to learn each model respectively.
This considerable time makes testing your method quite time-consuming. 

I believe that providing pre-trained checkpoints of your method would improve significance and applicability of your method. 

In this regard, I'd like to inquiry about the expected release date of the official checkpoints.
Their availability would greatly contribute to the efficiency of generative INR domains and enable meaningful progress in this field. 

Thanks.

**Comment by DogyunPark** [comment]
Thank you for your interest in our work.
We currently have a storage problem to release the checkpoints and expect it to take roughly a couple of days.

**Comment by MingyuKim87** [comment]
I appreciate the deployment of pre-trained checkpoints in this paper. 
I would like to ask you have a plan to distribute auto-encoder checkpoints, tough.

**Comment by DogyunPark** [comment]
Every auto-encoder model is loaded by a key value of 'vaemodel' in the code.

**Comment by MingyuKim87** [comment]
Thanks for letting me know that your shared checkpoint contains auto-encoder, decoder and diffusion model.
