### ISSUE TITLE
More implementation details about NeRF.

### ISSUE THREAD

**Issue by WeihangLiu2024** [mlvlab/DDMI#2]
Thks for the excellent work. 

Could you please show more details about the NeRF models? 

Here is my understanding, and I am not sure about this:
> "Specifically, we encode point clouds to the 2D-triplane HDBFs, allowing MLP to read out triplane features at queried coordinate and ray direction into color and density via neural rendering"
> It seems that the read-out MLP is frozen for all generated scenes (different cars in the paper). So DDMI only generate multi-resolution feature grid of different scenes, all of which share one fixed MLP.

Additionally, what is the input of encoder in the context of NeRF? It seems that a batch of (ray_o, ray_d) is the answer where training D2C-VAE is actually training NeRF (for a specific scene) from scratch, which means one MLP is tied to one specific scene.

**Comment by DogyunPark** [comment]
Thanks for your interest in our work.

While It is true that MLP is shared with different scenes, we generate sample-specific positional embeddings with diffusion models that enable our model to represent different scenes. This is the key idea of our work.

The input of the encoder is point clouds consisting of coordinates and RGB values (6 dimensions). In the first stage, D2C-VAE learns to map point clouds to NeRF, mostly following the setup from [https://github.com/gmum/points2nerf](https://github.com/gmum/points2nerf).
