### ISSUE TITLE
Experiments on WebVid-10M

### ISSUE THREAD

**Issue by skrya** [mlvlab/DDMI#3]
Dear Authors,

Thank you for your truly amazing work and for making the code public.

Have you conducted experiments on large video datasets such as WebVid-10M? If so, could you please share your findings? If not, could you explain the challenges you foresee in scaling up to such large datasets?

Thank you!

**Comment by DogyunPark** [comment]
Thanks for your interest in our work.
Due to our limited resources, we haven't tried scaling up our work to large-scale datasets such as WebVid-10M. We are planning to do it in the near future and hope to share our findings.

**Comment by DogyunPark** [comment]
Thanks for your interest.

Currently, we do not have enough resources to apply on large-scale datasets such as WebVid-10M.
One possible challenge might be a small MLP layer shared across different video scenes that may limit the capacity to represent them expressively. More efficient and expressive positional embedding and advanced architecture, such as a transformer, may further increase the performance on large-scale datasets.
