### ISSUE TITLE
About the loss

### ISSUE THREAD

**Issue by Lzyin** [mlvlab/DDMI#6]
Thank you for your interesting work. 

I have some confusion regarding the loss aspect. Specifically, is the objective of Eq. 9 to maximize the loss _L_? It seems so from the context of the article.

I sincerely hope to get your reply.

**Comment by DogyunPark** [comment]
Thanks for your interest in our work.

Yes. We update the parameters that maximize the objective in Eq.9.

**Comment by Lzyin** [comment]
Thank you for your reply. 

The point that confuses me is that Appendix B.1 also states "_minimize the re-weighted ELBO objective of D2C-VAE in Eq. 9._ "

**Comment by DogyunPark** [comment]
Sorry for the confusion.
It should be "maximize".
